language: python
python:
  - "3.3"
#  - "3.6"
env:
  - DOCKER_COMPOSE_VERSION=1.8.0
  - DOCKER_COMPOSE_VERSION=1.9.0
  - DOCKER_COMPOSE_VERSION=1.10.0
  - DOCKER_COMPOSE_VERSION=1.11.0
  - DOCKER_COMPOSE_VERSION=1.12.0
  - DOCKER_COMPOSE_VERSION=1.13.0
  - DOCKER_COMPOSE_VERSION=1.14.0
  - DOCKER_COMPOSE_VERSION=1.15.0
  - DOCKER_COMPOSE_VERSION=1.16.0
  - DOCKER_COMPOSE_VERSION=1.17.0
  - DOCKER_COMPOSE_VERSION=1.18.0
  - DOCKER_COMPOSE_VERSION=1.19.0
  - DOCKER_COMPOSE_VERSION=1.20.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - git clone --branch v0.4.0 https://github.com/sstephenson/bats.git
script:
  - ./bats/bin/bats tests.bats
sudo: required
services:
  - docker
