language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "pypy3.5"
env:
  - DOCKER_COMPOSE_VERSION=1.6.0
  - DOCKER_COMPOSE_VERSION=1.6.2
  - DOCKER_COMPOSE_VERSION=1.7.0
  - DOCKER_COMPOSE_VERSION=1.8.0
  - DOCKER_COMPOSE_VERSION=1.9.0
  - DOCKER_COMPOSE_VERSION=1.10.0
  - DOCKER_COMPOSE_VERSION=1.11.0
  - DOCKER_COMPOSE_VERSION=1.12.0
  - DOCKER_COMPOSE_VERSION=1.13.0
  - DOCKER_COMPOSE_VERSION=1.14.0
  - DOCKER_COMPOSE_VERSION=1.15.0
  - DOCKER_COMPOSE_VERSION=1.16.0
  - DOCKER_COMPOSE_VERSION=1.17.0
  - DOCKER_COMPOSE_VERSION=1.18.0
  - DOCKER_COMPOSE_VERSION=1.19.0
  - DOCKER_COMPOSE_VERSION=1.20.0
install:
  - git clone --branch v0.4.0 https://github.com/sstephenson/bats.git
script:
  - ./bats/bin/bats tests.bats
sudo: required
services:
  - docker
