language: python
python:
  - "3.3"
  - "3.6"
env:
  - DOCKER_COMPOSE_VERSION=1.0.0
  - DOCKER_COMPOSE_VERSION=1.1.0
  - DOCKER_COMPOSE_VERSION=1.2.0
  - DOCKER_COMPOSE_VERSION=1.3.0
  - DOCKER_COMPOSE_VERSION=1.4.0
  - DOCKER_COMPOSE_VERSION=1.5.0
  - DOCKER_COMPOSE_VERSION=1.20.0
install:
  - git clone --branch v0.4.0 https://github.com/sstephenson/bats.git
script:
  - ./bats/bin/bats tests.bats
sudo: required
services:
  - docker
