language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - git clone --branch v0.4.0 https://github.com/sstephenson/bats.git
script:
  - ./bats/bin/bats tests.bats
sudo: required
services:
  - docker
